# permissions for end users to view githubrepositories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: githubrepository-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: github
    app.kubernetes.io/part-of: github
    app.kubernetes.io/managed-by: kustomize
  name: githubrepository-viewer-role
rules:
  - apiGroups:
      - scm.greenhouse.sap
    resources:
      - githubrepositories
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - scm.greenhouse.sap
    resources:
      - githubrepositories/status
    verbs:
      - get
