---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  - apiGroups:
      - scm.greenhouse.sap
    resources:
      - githubrepositories
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - scm.greenhouse.sap
    resources:
      - githubrepositories/finalizers
    verbs:
      - update
  - apiGroups:
      - scm.greenhouse.sap
    resources:
      - githubrepositories/status
    verbs:
      - get
      - patch
      - update
